- name: "common tasks for all virtual machines"
  hosts: all
  become: yes
  tasks:
  - name: Installs useful packages
    apt:
      pkg:
      - git
      - nfs-common
      state: present
      update_cache: true

  - name: Populate the /etc/hosts with data from the inventory
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[item].ansible_host }} {{ item }}"
    loop: "{{ groups['all'] }}"
